### ISSUE TITLE
Implement South Korean NPKI based Authentication 

### ISSUE THREAD

**Issue by Alex4386** [meili-NG/meiliNG#15]
Reference:  
[https://openapi.kftc.or.kr/main](https://openapi.kftc.or.kr/main)

![telegram-cloud-photo-size-5-6287281842000341897-y](https://user-images.githubusercontent.com/27724108/113472906-13eee180-94a1-11eb-9715-3cb6cd8033a4.jpg)

**Comment by Alex4386** [comment]
Requested Signature Validity API

**Comment by Alex4386** [comment]
It seems KFTC rejected our API request. Locking this issue.

**Comment by Alex4386** [comment]
I might try to use the "Certification Operator" as South Korean Government's "Digital New-deal" non-sense, But I think NPKI based Authentication will be more hillarious.

**Comment by Alex4386** [comment]
Currently impossible at the moment due to KFTC regulations.

**Comment by Alex4386** [comment]
This can be now implemented via alternative signin implementation.

**Comment by Alex4386** [comment]
Reopening issue since Alternative Login with Kakao Cert was implemented in **Stella IT Accounts**

**Comment by Alex4386** [comment]
@Baw-Appie

**Comment by Alex4386** [comment]
Since Stella IT uses KRID for Alternative Login procedure, Can't it be used with one?

**Comment by Baw-Appie** [comment]
> Since Stella IT uses KRID for Alternative Login procedure, Can't it be used with one?

This could be implemented, but I'm not sure it should be implemented in Meiling because it is better to implement in an alternative authentication system like KRID.  
If we want to use NPKI Authentication for 2FA method, it should be implemented in Meiling. or just another sign in method, it should be implemented in alternative authentication system.

**Comment by Alex4386** [comment]
Just what I thought. Closing issue since this should be tracked on another repo
