### ISSUE TITLE
Is it possible to provide a test account?

### ISSUE THREAD

**Issue by zeroday0619** [meili-NG/meiliNG#47]
A publicly available test account is required for client unit testing.

This is an example that requires a publicly available test account.
[@zeroday0619/httpx-oauth/commit/c1a27f281e1d906cd50d16de0e88bd568eff4f1c](https://github.com/zeroday0619/httpx-oauth/commit/c1a27f281e1d906cd50d16de0e88bd568eff4f1c)

**Comment by Alex4386** [comment]
Duplicate of #28.
Closing issue.
