### ISSUE TITLE
Essential scopes doesn't setup upon installation

### ISSUE THREAD

**Issue by ldmsys** [meili-NG/meiliNG#49]
Essential scopes such as `openid`, `profile`, `email` doesn't setup since table `Permission` is empty on clean installation.

Please refer [OpenID Connect Spec](https://openid.net/specs/openid-connect-basic-1_0.html#Scopes) for details.

**Comment by Alex4386** [comment]
Setup script is currently planned at the moment. Maybe you can implement one for me. (preferably, with wizard for `.env` file) Assigning this issue to @ldmsys. You can implement this since we already have wizard-like flow on `yarn keygen`.

**Comment by Alex4386** [comment]
Check https://github.com/meili-NG/meiliNG/blob/staging/keygen.js. And don't forget to target `staging` branch. That's where 0.9.0 development is going on at the moment.

**Comment by Alex4386** [comment]
**STUB** implemented on 15e441d458a28448ad81898b387bff7bb33854e6

**Comment by Alex4386** [comment]
Implmented @ https://github.com/meili-NG/meiliNG/blame/staging/configure.js

Closing Issue
